# Generated by Django 5.1.1 on 2024-09-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('ready', 'Готов'), ('in_progress', 'Готовится'), ('cancelled', 'Отклонен'), ('completed', 'Завершен')], max_length=11),
        ),
    ]
