# Generated by Django 5.1.1 on 2024-09-23 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time_completed',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='time_created',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='time_prepared',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
